version: "3"
services:

    api:
      build:
        context: ./api
      ports:
        - "1337:1337"

    client:
      build:
        context: ./client
      ports:
        - "3000:3000"
      environment:
        - REACT_APP_API_ROOT=localhost:1337
      stdin_open: true
